config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "application_forms#index"
  resources :application_forms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_form.rb
class ApplicationForm < ApplicationRecord
  enum english_level: [ :beginner, :elementary, :pre_intermediate ]  

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :application_form, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :set_application_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /application_forms
  # GET /application_forms.json
  def index
    @application_forms = ApplicationForm.all
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
  end

  # GET /application_forms/new
  def new
    @application_form = ApplicationForm.new
  end

  # GET /application_forms/1/edit
  def edit
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(application_form_params)

    respond_to do |format|
      if @application_form.save
        format.html { redirect_to @application_form, notice: 'Application form was successfully created.' }
        format.json { render :show, status: :created, location: @application_form }
      else
        format.html { render :new }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_forms/1
  # PATCH/PUT /application_forms/1.json
  def update
    authorize @application_form, :update?
    respond_to do |format|
      if @application_form.update(application_form_params)
        format.html { redirect_to @application_form, notice: 'Application form was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_form }
      else
        format.html { render :edit }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form.destroy
    respond_to do |format|
      format.html { redirect_to application_forms_url, notice: 'Application form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_form_params
      params.require(:application_form)
      .permit(:user_id, :email, :first_name, :last_name, :age, :interests, :english_level, :experience, :motivation)
      .merge(user_id: current_user.id)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application_forms/_form.html.erb
<div class="ui grid">
  <div class="five wide column">
    <%= form_for application_form, html: {class: 'ui form' } do |f| %>
      <% if application_form.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(application_form.errors.count, "error") %> prohibited this application_form from being saved:</h2>

          <ul>
          <% application_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :email, "E-mail" %>
        <%= f.text_field :email, required: true %>
      </div>

      <div class="field">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, required: true %>
      </div>

      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, required: true %>
      </div>

      <div class="field">
        <%= f.label :age %>
        <%= f.number_field :age, required: true %>
      </div>

      <div class="field">
        <%= f.label :interests %>
        <%= f.text_area :interests %>
      </div>

      <div class="field">
        <%= f.label :english_level %>
        <!-- <%= f.number_field :english_level %> -->
        <%= f.select(:english_level, ApplicationForm.english_levels.keys.map {|key| [key.humanize, key]}) %>
      </div>

      <div class="field">
        <%= f.label :experience %>
        <%= f.text_area :experience %>
      </div>

      <div class="field">
        <%= f.label :motivation %>
        <%= f.text_area :motivation %>
      </div>

      <div class="actions">
        <%= f.submit 'Submit', class: 'ui blue basic button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/application_forms/edit.html.erb
<div class="ui top attached menu">
  <%= link_to application_forms_path, class: 'ui icon item' do %>
    <i class="chevron left icon"></i>
  <% end %>
  <div class="header item">
    Editing Application Form
  </div>
    <%= link_to 'Show', @application_form, class: 'ui icon item' %>
</div>
<br>
<%= render 'form', application_form: @application_form %>

app/views/application_forms/index.html.erb
<% if notice.present? %>
  <div class="ui positive message">
    <div class="header">
      <%= notice %>
    </div>
  </div>
<% end %>

<h1>Application Forms</h1>

<div class="ui info message">
  <div class="header">
    Are you ready to join my educational project? If yes, fill in this application form :)
  </div>
</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Interests</th>
      <th>English level</th>
      <th>Experience</th>
      <th>Motivation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td><%= application_form.email %></td>
        <td><%= application_form.first_name %></td>
        <td><%= application_form.last_name %></td>
        <td><%= application_form.age %></td>
        <td><%= application_form.interests %></td>
        <td><%= application_form.english_level %></td>
        <td><%= application_form.experience %></td>
        <td><%= application_form.motivation %></td>
        <td>
          <%= link_to application_form, class: 'ui primary button' do %>
            <i class="file text outline icon"></i>
            Show
          <% end %>
        </td>
        <td>
          <%= link_to edit_application_form_path(application_form), class: 'ui positive button' do %>
            <i class="write icon"></i>
            Edit
          <% end %>
        </td>
        <td>
          <%= link_to application_form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui negative button' do %>
            <i class="trash outline icon"></i>
            Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_application_form_path, class: 'ui violet basic button' do %>
  <i class="add circle icon"></i>
  New Application Form
<% end %>

app/views/application_forms/new.html.erb
<div class="ui top attached menu">
  <%= link_to application_forms_path, class: 'ui icon item' do %>
    <i class="chevron left icon"></i>
  <% end %>
  <div class="header item">
    New Application Form
  </div>
</div>
<br>
<%= render 'form', application_form: @application_form %>

app/views/application_forms/show.html.erb
<div class="ui top attached menu">
  <%= link_to application_forms_path, class: 'ui icon item' do %>
    <i class="chevron left icon"></i>
  <% end %>
  <div class="header item">
    Application Form
  </div>
  <%= link_to edit_application_form_path(@application_form), class: 'ui icon item' do %>
    <i class="write icon"></i>
    &nbsp;
    Edit
  <% end %>
</div>
<div class="ui card">
  <div class="content">
    <div class="header"><%= @application_form.first_name %> <%= @application_form.last_name %></div>
    <div class="meta">
        <%= @application_form.email %>
    </div>
    <div class="description">
      <p>
        <strong>Age:</strong>
        <%= @application_form.age %>
      </p>

      <p>
        <strong>Interests:</strong>
        <%= @application_form.interests %>
      </p>

      <p>
        <strong>English level:</strong>
        <%= @application_form.english_level %>
      </p>

      <p>
        <strong>Experience:</strong>
        <%= @application_form.experience %>
      </p>

      <p>
        <strong>Motivation:</strong>
        <%= @application_form.motivation %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anketa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>